-- AlterTable
ALTER TABLE `UserGoal` MODIFY `category` ENUM('GENERAL', 'ACTIVITY', 'DPV', 'NEWS', 'BILLED', 'ASSIGNMENT', 'LOCATED_TENANTS', 'ADDED_PHONES', 'EMPTY_PROPERTIES', 'NEW_PROPERTIES') NOT NULL DEFAULT 'GENERAL';
